-- PAINEL CD T3 - BANCO COMPLETO
create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('armazenistas','empilhadores')),
  name text not null,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique(category,name)
);

create table if not exists public.settings (
  key text primary key,
  value text not null
);

insert into public.settings(key,value) values
('goal_armazenistas','150'),
('goal_empilhadores','150'),
('slide_seconds','10'),
('yellow_threshold','80'),
('image_armazenistas',''),
('image_empilhadores',''),
('shift_name','3º Turno'),
('anomaly_limit','5000'),
('presentation_paused','false'),
('forced_slide','aviso')
on conflict(key) do nothing;

create table if not exists public.production (
  id bigint generated by default as identity primary key,
  production_date date not null,
  category text not null check (category in ('armazenistas','empilhadores')),
  employee_id bigint not null references public.employees(id) on delete cascade,
  quantity integer not null default 0 check (quantity >= 0),
  updated_by uuid null references auth.users(id),
  updated_at timestamptz not null default now(),
  unique(production_date, category, employee_id)
);

create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  notice_type text not null default 'AVISO',
  title text not null,
  message text not null default '',
  author text not null default 'CD T3',
  priority integer not null default 10,
  active boolean not null default true,
  image_url text,
  updated_by uuid null references auth.users(id),
  updated_at timestamptz not null default now()
);

create table if not exists public.extra_pages (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text default '',
  message text default '',
  theme text not null default 'green' check(theme in ('green','blue','orange','dark')),
  image_url text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

insert into public.notices(notice_type,title,message,author,priority)
select 'AVISO','Bem-vindos ao turno!','Bom trabalho a todos. Segurança e qualidade em primeiro lugar.','CD T3',10
where not exists(select 1 from public.notices);

insert into public.employees(category,name,sort_order) values
('armazenistas','Lucas',1),('armazenistas','Fernando',2),('armazenistas','Flávio J. da Silva Pereira',3),
('armazenistas','Edmar Alves Teixeira',4),('armazenistas','Mateus Gonzaga de Lacerda',5),
('armazenistas','Fernando Franco de Oliveira',6),('armazenistas','Ari da Silva Santos',7),
('armazenistas','Weligton dos Santos',8),('armazenistas','Henrique Soares dos Santos',9),
('armazenistas','José Rogério Napoleão',10),('armazenistas','Andrio L. Santos de Moraes',11),
('armazenistas','Henrique da Silva Stoski',12)
on conflict(category,name) do update set sort_order=excluded.sort_order;

insert into public.employees(category,name,sort_order) values
('empilhadores','Lucas',1),('empilhadores','Fernando',2),('empilhadores','Flávio',3),
('empilhadores','Edmar',4),('empilhadores','Mateus',5),('empilhadores','Fernando Franco',6),
('empilhadores','Ari',7),('empilhadores','Weligton',8),('empilhadores','Henrique Soare',9),
('empilhadores','José',10),('empilhadores','Andrio',11),('empilhadores','Henrique Stosq',12)
on conflict(category,name) do update set sort_order=excluded.sort_order;

create or replace view public.production_view as
select p.production_date,p.category,p.employee_id,e.name as employee_name,p.quantity,p.updated_at
from public.production p join public.employees e on e.id=p.employee_id where e.active=true;

alter table public.employees enable row level security;
alter table public.settings enable row level security;
alter table public.production enable row level security;
alter table public.notices enable row level security;
alter table public.extra_pages enable row level security;

drop policy if exists "employees read" on public.employees;
create policy "employees read" on public.employees for select using(true);
drop policy if exists "settings read" on public.settings;
create policy "settings read" on public.settings for select using(true);
drop policy if exists "production read" on public.production;
create policy "production read" on public.production for select using(true);
drop policy if exists "notices read" on public.notices;
create policy "notices read" on public.notices for select using(true);
drop policy if exists "extra pages read" on public.extra_pages;
create policy "extra pages read" on public.extra_pages for select using(true);

drop policy if exists "settings write" on public.settings;
create policy "settings write" on public.settings for all to authenticated using(true) with check(true);
drop policy if exists "production write" on public.production;
create policy "production write" on public.production for all to authenticated using(true) with check(true);
drop policy if exists "notices write" on public.notices;
create policy "notices write" on public.notices for all to authenticated using(true) with check(true);
drop policy if exists "extra pages write" on public.extra_pages;
create policy "extra pages write" on public.extra_pages for all to authenticated using(true) with check(true);


drop policy if exists "employees write" on public.employees;
create policy "employees write" on public.employees
for update to authenticated
using(true)
with check(true);


drop policy if exists "employees insert" on public.employees;
create policy "employees insert" on public.employees
for insert to authenticated
with check(true);

drop policy if exists "employees delete" on public.employees;
create policy "employees delete" on public.employees
for delete to authenticated
using(true);


grant select on public.production_view to anon,authenticated;

-- Storage para imagens
insert into storage.buckets(id,name,public)
values('panel-media','panel-media',true)
on conflict(id) do update set public=true;

drop policy if exists "panel media public read" on storage.objects;
create policy "panel media public read" on storage.objects for select using(bucket_id='panel-media');

drop policy if exists "panel media authenticated insert" on storage.objects;
create policy "panel media authenticated insert" on storage.objects for insert to authenticated with check(bucket_id='panel-media');

drop policy if exists "panel media authenticated update" on storage.objects;
create policy "panel media authenticated update" on storage.objects for update to authenticated using(bucket_id='panel-media') with check(bucket_id='panel-media');

drop policy if exists "panel media authenticated delete" on storage.objects;
create policy "panel media authenticated delete" on storage.objects for delete to authenticated using(bucket_id='panel-media');

-- Realtime: rode estas linhas apenas se as tabelas ainda não estiverem na publication.
-- Se aparecer "already member of publication", ignore somente a linha correspondente.
alter publication supabase_realtime add table public.production;
alter publication supabase_realtime add table public.settings;
alter publication supabase_realtime add table public.notices;
alter publication supabase_realtime add table public.extra_pages;


drop policy if exists "notices delete" on public.notices;
create policy "notices delete"
on public.notices
for delete
to authenticated
using (true);
